- name: Fetch MicroK8s Kubeconfig
  hosts: all
  tasks:
    - name: Get MicroK8s Kubeconfig
      command: sudo microk8s config
      register: kubeconfig_output

    - name: Ensure .kube directory exists on local machine
      delegate_to: localhost
      file:
        path: "~/.kube"
        state: directory
        mode: '0700'

    - name: Save kubeconfig to local file
      delegate_to: localhost
      copy:
        content: "{{ kubeconfig_output.stdout }}"
        dest: "~/.kube/config"
        mode: '0600'
